language: node_js
node_js:
- 9
install:
  - pip install --user awscli
script: exit 0
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: www.mmoreno23.net 
  local-dir: ./
  skip_cleanup: true
  region: $AWS_DEFAULT_REGION
  on:
    branch: master
